# workflow 工作流的名字，自定义
name: hello express

# 配置触发条件
on:
  push: # 监听到 main 分支的 push 动作
    branches:
      - main

# 工作流的任务集配置
jobs:
  # 定义一个 job，id 为 build
  build:
    # 指定任务执行的运行器。latest 表示是 GitHub 提供的最新稳定映像，但可能不是操作系统供应商提供的最新版本.
    runs-on: ubuntu-latest

    # 定义 job 的具体步骤
    steps: # 每一个 step 或者是执行一个 action，或者是执行一个命令
      - name: Checkout # 从仓库中检出代码，供下一步使用
        uses: actions/checkout@v3

      - name: Deploy to Server # 执行部署任务
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            ssh root@${{ secrets.SERVER_HOST }} 'docker stop my_container || true && docker rm my_container || true'
            ssh root@${{ secrets.SERVER_HOST }} 'docker pull your_docker_image'
            ssh root@${{ secrets.SERVER_HOST }} 'docker run -d --name my_container -p 3000:3000 your_docker_image'

